@port = 62581
@host = http://localhost:{{port}}
@companyId = 98f0abb6-26ec-4d85-84cd-d7adde81cd10
@userId = 00000000-0000-0000-0000-000000000000
@role = ADMIN

### 회사 생성
POST {{host}}/companies
Content-Type: application/json
X-User-Id: {{userId}}
X-User-Role: {{role}}

{
  "name": "테스트 회사1",
  "businessNumber": "123-456",
  "description": "설명",
  "email": "test@test.com",
  "phone": "010-1234-5678"
}

###

### 회사 조회
GET {{host}}/companies/{{companyId}}
X-User-Id: {{userId}}
X-User-Role: {{role}}