@port = 8080
@host = http://localhost:{{port}}
@companyId = 04041064-ca5f-4569-9d6f-519731ccaff8

### 회사 생성
POST {{host}}/companies
Content-Type: application/json

{
  "name": "테스트 회사3",
  "businessNumber": "123-45678",
  "description": "설명",
  "email": "test@test.com",
  "phone": "010-1234-5678"
}

###

### 회사 조회
GET {{host}}/companies/{{companyId}}