@port = 58576
@host = http://localhost:{{port}}
@companyId = 278a96ab-0527-492e-9e96-b4bd0235ddb8
@userId = 00000000-0000-0000-0000-000000000000
@productId = f115373c-ca77-4cd8-9f81-2b62318e71ab
@scheduleId = a0969ec0-1eb5-466d-a2b1-004a3b8788eb

### 상품 생성
POST {{host}}/products
Content-Type: application/json
X-User-Id: {{userId}}
X-Company-Id: {{companyId}}

{
  "productName": "테스트 상품3",
  "description": "테스트 상품 설명",
  "country": "KR",
  "state": "서울특별시",
  "city": "강남구",
  "addressLine": "테헤란로 123",
  "price": 10000.00
}

### 상품 단건 조회
GET {{host}}/products/{{productId}}

###

### 상품 목록 조회
GET {{host}}/products?page=0&size=10&sort=createdAt,desc

### 상품 스케줄 일괄 생성
POST {{host}}/products/{{productId}}/schedules/bulk
Content-Type: application/json

{
  "startDate": "2026-05-01",
  "endDate": "2026-05-05",
  "stock": 10
}

### 스케줄 목록 조회
GET {{host}}/products/{{productId}}/schedules?page=0&size=10


### 스케줄 단건 조회
GET {{host}}/products/{{productId}}/schedules/{{scheduleId}}